name: Lobby
version: '${project.version}'
main: de.murmelmeister.lobby.Lobby
api-version: '1.20'
author: Murmelmeister
website: https://www.youtube.com/Murmelmeister

commands:
  setspawn:
    usage: /setspawn
    description: Set the spawn.
  spawn:
    usage: /spawn
    description: Teleports you to the spawn.
  build:
    usage: /build [player]
    description: Set you in the build mode.