name: CityBuild
version: '${project.version}'
main: de.murmelmeister.citybuild.CityBuild
api-version: '1.20'
author: Murmelmeister
website: https://www.youtube.com/Murmelmeister

commands:
  enderchest:
    usage: /enderchest [PLAYER]
    description: Opens the EnderChest.
    aliases:
      - ec
  citybuildreload:
    usage: /citybuildrelaod
    description: Reload the configuration.
    aliases:
      - cbreload
      - cbrl
  setspawn:
    usage: /setspawn
    description: Set the spawn.
  spawn:
    usage: /spawn
    description: Teleports you to the spawn.
  removewarp:
    usage: /removewarp <LOCATION>
    description: Remove the location.
    aliases:
      - rmwarp
  setwarp:
    usage: /setwarp <LOCATION>
    description: Set the location.
  warp:
    usage: /warp <LOCATION>
    description: Teleports you to the location.