name: CityBuild
version: '${project.version}'
main: de.murmelmeister.citybuild.CityBuild
api-version: '1.20'
author: Murmelmeister
website: https://www.youtube.com/Murmelmeister

commands:
  enderchest:
    usage: /enderchest [player]
    description: Opens the EnderChest.
    aliases:
      - ec
  citybuildreload:
    usage: /citybuildrelaod
    description: Reload the configuration.
    aliases:
      - cbreload
      - cbrl
  setspawn:
    usage: /setspawn
    description: Set the spawn.
  spawn:
    usage: /spawn
    description: Teleports you to the spawn.
  removewarp:
    usage: /removewarp <location>
    description: Remove the location.
    aliases:
      - rmwarp
      - deletewarp
      - delwarp
  setwarp:
    usage: /setwarp <location>
    description: Set the location.
  warp:
    usage: /warp <location>
    description: Teleports you to the location.
  addhome:
    usage: /addhome <home>
    description: Add a new home.
  home:
    usage: /home <home>
    description: Teleport you to your home.
  removehome:
    usage: /removehome <home>
    description: Delete a home.
    aliases:
      - rmhome
      - deletehome
      - delhome
  workbench:
    usage: /workbench
    description: Opens the workbench.
    aliases:
      - wb
  anvil:
    usage: /anvil
    description: Opens the anvil.
    aliases:
      - av
  trash:
    usage: /trash
    description: Opens the trash.
  feed:
    usage: /feed [player]
    description: Feed your hunger.
  heal:
    usage: /heal [player]
    description: Heal you.
  fly:
    usage: /fly [player]
    description: Active the fly mode.
  godmode:
    usage: /godmode [player]
    description: Active the god mode.